name: Build

on:
    pull_request:
      branches:
        - main

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/ci:v0.26.2 
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Initialize
        run: |
          west init -l .
          west update -o=--depth=1 -n

      - name: Build example
        run: |
          ls -la
          west build -b swan_r5 example